"""Prescription lifecycle: compose, check, issue, print, send."""
import asyncio
import hashlib
import hmac
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.config import settings
from app.core.logging import get_logger
from app.departments import code_for, label_for
from app.messaging.base import OutboundDocument
from app.models.enums import (
    DeliveryChannel,
    Department,
    PrescriptionStatus,
)
from app.models.patient import Patient
from app.models.prescription import MessageDelivery, Prescription, PrescriptionMedicine
from app.prescriptions import safety
from app.prescriptions.dictation import parse_dictation
from app.prescriptions.pdf import (
    PdfUnavailableError,
    PrescriptionDocument,
    render_prescription_pdf,
)
from app.repositories.consultation_repository import ConsultationRepository
from app.repositories.patient_repository import PatientRepository
from app.services.delivery_service import DeliveryService

logger = get_logger(__name__)

# Both come from the department registry, so a new speciality cannot end up
# numbering its prescriptions under another department's code.
DEPARTMENT_LABELS = {d: label_for(d) for d in Department}
DEPARTMENT_CODES = {d: code_for(d) for d in Department}


class PrescriptionError(Exception):
    pass


class PrescriptionService:
    def __init__(self, session: AsyncSession) -> None:
        self.session = session
        self.patients = PatientRepository(session)
        self.consultations = ConsultationRepository(session)
        self.deliveries = DeliveryService(session)

    # -------------------------------------------------------------- helpers
    @staticmethod
    def pdf_path(filename: str) -> Path:
        return Path(settings.MEDIA_ROOT) / "prescriptions" / filename

    @staticmethod
    def signature_path(user_id: uuid.UUID) -> Path:
        return Path(settings.MEDIA_ROOT) / "signatures" / f"{user_id}.png"

    async def _next_number(self, department: Department) -> str:
        """SH-ORT-2026-000123 — readable, sortable, unique per year."""
        year = datetime.now(timezone.utc).year
        prefix = f"{settings.PRESCRIPTION_NUMBER_PREFIX}-{DEPARTMENT_CODES[department]}-{year}-"
        result = await self.session.execute(
            select(func.count())
            .select_from(Prescription)
            .where(Prescription.prescription_number.like(f"{prefix}%"))
        )
        return f"{prefix}{int(result.scalar_one()) + 1:06d}"

    # ------------------------------------------------- signed document links
    @staticmethod
    def sign_document_token(prescription_id: uuid.UUID, expires_at: int) -> str:
        message = f"{prescription_id}:{expires_at}".encode()
        digest = hmac.new(
            settings.JWT_SECRET_KEY.encode(), message, hashlib.sha256
        ).hexdigest()[:32]
        return f"{expires_at}.{digest}"

    @staticmethod
    def verify_document_token(prescription_id: uuid.UUID, token: str) -> bool:
        """Constant-time check of an expiring, unguessable document link.

        Providers such as Twilio fetch media anonymously, so the link cannot
        require a bearer token — it is scoped to one prescription and expires.
        """
        try:
            raw_expiry, _, digest = token.partition(".")
            expires_at = int(raw_expiry)
        except (ValueError, AttributeError):
            return False
        if expires_at < int(time.time()):
            return False
        expected = PrescriptionService.sign_document_token(prescription_id, expires_at)
        return hmac.compare_digest(expected, token)

    def public_document_url(self, prescription_id: uuid.UUID) -> str:
        expires_at = int(time.time()) + settings.DOCUMENT_LINK_TTL_S
        token = self.sign_document_token(prescription_id, expires_at)
        base = settings.PUBLIC_BASE_URL.rstrip("/")
        return f"{base}/api/v1/public/prescriptions/{prescription_id}/pdf?token={token}"

    # ------------------------------------------------------------- dictation
    @staticmethod
    def parse_dictation_text(transcript: str) -> List[Dict[str, Any]]:
        return [medicine.to_dict() for medicine in parse_dictation(transcript)]

    # --------------------------------------------------------------- prefill
    async def prefill_from_consultation(
        self, consultation_id: uuid.UUID
    ) -> Dict[str, Any]:
        """Compose the clinical half of a prescription from the AI dossier.

        Everything here was already generated by the intake pipeline, so this
        is a deterministic projection of existing data rather than a fresh
        model call — instant, free, and it cannot contradict what the doctor
        already reviewed on the consultation page.

        Medicines are deliberately NOT prefilled. Drug choice is the
        prescriber's decision; the AI prepares the paperwork around it.
        """
        consultation = await self.consultations.get(consultation_id)
        if consultation is None:
            return {}

        dossier = consultation.medical_json or {}
        record = dossier.get("medical_json") or {}
        summary = dossier.get("clinical_summary") or {}
        risk = dossier.get("risk_assessment") or {}
        differentials = (dossier.get("differential_diagnosis") or {}).get(
            "differentials"
        ) or []
        investigations = (dossier.get("investigations") or {}).get(
            "investigations"
        ) or []

        # Diagnosis: the leading differential is the AI's best reading, but it
        # is a suggestion, so it is marked provisional for the doctor to accept
        # or overwrite rather than presented as settled.
        diagnosis = ""
        if differentials:
            leading = differentials[0]
            condition = str(leading.get("condition") or "").strip()
            if condition:
                likelihood = str(leading.get("likelihood") or "").strip()
                diagnosis = (
                    f"{condition} (AI suggestion — {likelihood} likelihood; confirm)"
                    if likelihood else f"{condition} (AI suggestion — confirm)"
                )
        if not diagnosis:
            diagnosis = str(summary.get("one_liner") or record.get("chief_complaint") or "")

        # Cause: whatever the differential identified as the driver, falling
        # back to the reasoning note.
        cause = ""
        if differentials:
            supporting = differentials[0].get("supporting_features") or []
            if supporting:
                cause = "; ".join(str(item) for item in supporting[:3])
        if not cause:
            cause = str((dossier.get("differential_diagnosis") or {}).get("reasoning_note") or "")

        # Clinical findings: the history plus anything flagged as a red flag,
        # since those are what a reader of the sheet most needs to see.
        findings_parts = []
        if summary.get("history_of_present_illness"):
            findings_parts.append(str(summary["history_of_present_illness"]))
        positives = summary.get("pertinent_positives") or []
        if positives:
            findings_parts.append("Positives: " + ", ".join(str(x) for x in positives))
        negatives = summary.get("pertinent_negatives") or []
        if negatives:
            findings_parts.append("Negatives: " + ", ".join(str(x) for x in negatives))
        flags = [str(f.get("flag") or "") for f in (risk.get("red_flags") or [])]
        flags = [f.replace("_", " ").title() for f in flags if f]
        if flags:
            findings_parts.append("Red flags: " + ", ".join(flags))

        # Investigations the doctor actually ordered come first and are what
        # matter: the printed prescription is the only thing the patient
        # physically carries to the laboratory, so an order that exists solely
        # in the database would never reach anyone.
        ordered = await self._ordered_investigations(consultation_id)
        suggested = [str(item.get("test")) for item in investigations if item.get("test")]
        merged = list(ordered)
        for test in suggested:
            if test and test.lower() not in {o.lower() for o in merged}:
                merged.append(test)

        return {
            "diagnosis": diagnosis.strip(),
            "cause": cause.strip(),
            "chief_complaint": str(record.get("chief_complaint") or "").strip(),
            "clinical_findings": "\n".join(findings_parts).strip(),
            "investigations": merged,
            "investigations_ordered": ordered,
            "investigations_suggested": [t for t in suggested if t not in ordered],
            "general_instructions": self._education_advice(dossier),
            "follow_up_notes": str(risk.get("recommended_action") or "").strip(),
            "allergies": [str(a) for a in (record.get("allergies") or [])],
            "current_medicines": [
                {"name": m.get("name"), "dose_or_frequency": m.get("dose_or_frequency")}
                for m in (record.get("current_medicines") or [])
                if isinstance(m, dict) and m.get("name")
            ],
            "source": "ai_dossier",
        }

    async def _ordered_investigations(self, consultation_id: uuid.UUID) -> List[str]:
        """Names of every investigation ordered on this consultation.

        Cancelled slips are skipped; preparation instructions are appended so
        the patient reads "12 hours fasting" on the same sheet that tells them
        which test to have.
        """
        from app.repositories.investigation_repository import (
            InvestigationOrderRepository,
        )

        repository = InvestigationOrderRepository(self.session)
        orders = await repository.list_for(consultation_id=consultation_id)
        names: List[str] = []
        for order in orders:
            if order.status.value == "cancelled":
                continue
            for item in order.items:
                label = item.name
                if item.preparation:
                    label = f"{label} — {item.preparation}"
                if label not in names:
                    names.append(label)
        return names

    @staticmethod
    def _education_advice(dossier: Dict[str, Any]) -> str:
        """Patient-facing advice already written by the education stage."""
        education = dossier.get("patient_education") or {}
        parts = []
        for tip in (education.get("general_self_care") or [])[:4]:
            parts.append(str(tip))
        warnings = education.get("warning_signs_return_immediately") or []
        if warnings:
            parts.append(
                "Return immediately if: " + "; ".join(str(w) for w in warnings[:4])
            )
        return " ".join(parts).strip()

    # ---------------------------------------------------------------- safety
    async def run_safety(
        self, patient_id: uuid.UUID, medicines: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        patient = await self.patients.get(patient_id)
        allergies = await self._known_allergies(patient_id)
        pregnancy_possible = await self._pregnancy_possible(patient_id, patient)
        alerts = safety.run_all(
            medicines, allergies=allergies, pregnancy_possible=pregnancy_possible
        )
        return [alert.to_dict() for alert in alerts]

    async def _known_allergies(self, patient_id: uuid.UUID) -> List[str]:
        """Allergies accumulated across every prior consultation dossier."""
        consultations = await self.consultations.list_paginated(
            patient_id=patient_id, limit=50
        )
        found: List[str] = []
        for consultation in consultations[0]:
            record = (consultation.medical_json or {}).get("medical_json") or {}
            for allergy in record.get("allergies") or []:
                text = str(allergy).strip()
                if text and text.lower() not in {item.lower() for item in found}:
                    found.append(text)
        return found

    async def _pregnancy_possible(
        self, patient_id: uuid.UUID, patient: Optional[Patient]
    ) -> bool:
        if patient is None or patient.gender.value != "female":
            return False
        if patient.age is not None and not (12 <= patient.age <= 55):
            return False
        consultations = await self.consultations.list_paginated(
            patient_id=patient_id, limit=10
        )
        for consultation in consultations[0]:
            record = (consultation.medical_json or {}).get("medical_json") or {}
            specific = record.get("department_specific") or {}
            value = str(
                specific.get("pregnancy_possible")
                or specific.get("pregnancy_possibility")
                or ""
            ).lower()
            if value in {"yes", "true", "possible", "confirmed"}:
                return True
        return False

    # ---------------------------------------------------------------- create
    async def create(
        self,
        *,
        patient_id: uuid.UUID,
        consultation_id: Optional[uuid.UUID],
        department: Department,
        doctor_id: uuid.UUID,
        doctor_name: str,
        doctor_qualification: Optional[str],
        doctor_registration: Optional[str],
        medicines: List[Dict[str, Any]],
        diagnosis: Optional[str],
        cause: Optional[str],
        chief_complaint: Optional[str],
        clinical_findings: Optional[str],
        investigations: List[str],
        general_instructions: Optional[str],
        follow_up_notes: Optional[str],
        follow_up_date: Optional[datetime],
        dictation_transcript: Optional[str],
        acknowledged_alerts: List[Dict[str, Any]],
        issue: bool,
    ) -> Prescription:
        patient = await self.patients.get(patient_id)
        if patient is None:
            raise PrescriptionError("Patient not found.")
        if issue and not medicines:
            raise PrescriptionError("A prescription needs at least one medicine.")
        if issue and not (diagnosis or "").strip():
            raise PrescriptionError("Confirm the diagnosis before issuing.")

        # Serious alerts must be explicitly acknowledged before issuing.
        if issue:
            alerts = safety.run_all(
                medicines,
                allergies=await self._known_allergies(patient_id),
                pregnancy_possible=await self._pregnancy_possible(patient_id, patient),
            )
            blocking = safety.blocking_alerts(alerts)
            acknowledged = {
                (item.get("kind"), tuple(sorted(item.get("medicines") or [])))
                for item in acknowledged_alerts
            }
            unacknowledged = [
                alert for alert in blocking
                if (alert.kind, tuple(sorted(alert.medicines))) not in acknowledged
            ]
            if unacknowledged:
                raise PrescriptionError(
                    "Acknowledge these safety warnings before issuing: "
                    + "; ".join(alert.description for alert in unacknowledged)
                )

        prescription = Prescription(
            prescription_number=await self._next_number(department),
            patient_id=patient_id,
            consultation_id=consultation_id,
            doctor_id=doctor_id,
            doctor_name=doctor_name,
            doctor_qualification=doctor_qualification,
            doctor_registration=doctor_registration,
            department=department,
            status=PrescriptionStatus.ISSUED if issue else PrescriptionStatus.DRAFT,
            diagnosis=diagnosis,
            cause=cause,
            chief_complaint=chief_complaint,
            clinical_findings=clinical_findings,
            investigations_advised=investigations,
            general_instructions=general_instructions,
            follow_up_notes=follow_up_notes,
            follow_up_date=follow_up_date,
            dictation_transcript=dictation_transcript,
            acknowledged_alerts=acknowledged_alerts,
            issued_at=datetime.now(timezone.utc) if issue else None,
        )
        self.session.add(prescription)
        await self.session.flush()

        for position, entry in enumerate(medicines):
            self.session.add(
                PrescriptionMedicine(
                    prescription_id=prescription.id,
                    position=position,
                    formulary_code=entry.get("formulary_code"),
                    name=(entry.get("name") or "").strip()[:255],
                    generic=entry.get("generic"),
                    form=entry.get("form"),
                    strength=entry.get("strength"),
                    dosage=entry.get("dosage"),
                    frequency_code=entry.get("frequency_code"),
                    frequency_text=entry.get("frequency_text"),
                    duration=entry.get("duration"),
                    timing=entry.get("timing"),
                    route=entry.get("route"),
                    instructions=entry.get("instructions"),
                    source=entry.get("source") or "manual",
                )
            )
        await self.session.commit()

        if issue:
            await self.generate_pdf(prescription.id)
        logger.info(
            "prescription_created",
            extra={
                "prescription_id": str(prescription.id),
                "number": prescription.prescription_number,
                "medicines": len(medicines),
                "issued": issue,
            },
        )
        return await self.get(prescription.id)

    # ------------------------------------------------------------------- pdf
    async def generate_pdf(self, prescription_id: uuid.UUID) -> Optional[Prescription]:
        prescription = await self.get(prescription_id)
        if prescription is None:
            return None
        patient = await self.patients.get(prescription.patient_id)
        allergies = await self._known_allergies(prescription.patient_id)

        signature = None
        if prescription.doctor_id:
            candidate = self.signature_path(prescription.doctor_id)
            if candidate.exists():
                signature = str(candidate)

        verify_url = (
            f"{settings.PUBLIC_BASE_URL.rstrip('/')}/verify/{prescription.prescription_number}"
        )
        document = PrescriptionDocument(
            prescription_number=prescription.prescription_number,
            issued_at=prescription.issued_at or prescription.created_at,
            department_label=DEPARTMENT_LABELS[prescription.department],
            doctor_name=prescription.doctor_name,
            doctor_qualification=prescription.doctor_qualification,
            doctor_registration=prescription.doctor_registration,
            patient_name=patient.name if patient else "—",
            patient_age=patient.age if patient else None,
            patient_gender=patient.gender.value if patient else None,
            patient_phone=patient.phone_number if patient else None,
            patient_id_label=(
                f"Patient ID: {str(patient.id)[:8].upper()}" if patient else None
            ),
            diagnosis=prescription.diagnosis,
            cause=prescription.cause,
            chief_complaint=prescription.chief_complaint,
            clinical_findings=prescription.clinical_findings,
            investigations=list(prescription.investigations_advised or []),
            medicines=[
                {
                    "name": medicine.name,
                    "form": medicine.form,
                    "strength": medicine.strength,
                    "generic": medicine.generic,
                    "dosage": medicine.dosage,
                    "frequency_text": medicine.frequency_text,
                    "frequency_code": medicine.frequency_code,
                    "duration": medicine.duration,
                    "timing": medicine.timing,
                    "route": medicine.route,
                    "instructions": medicine.instructions,
                }
                for medicine in prescription.medicines
            ],
            general_instructions=prescription.general_instructions,
            follow_up=self._follow_up_text(prescription),
            qr_payload=verify_url,
            signature_path=signature,
            allergies=allergies,
        )

        try:
            # ReportLab is CPU-bound; render in a worker thread.
            content = await asyncio.to_thread(render_prescription_pdf, document)
        except PdfUnavailableError as exc:
            raise PrescriptionError(str(exc)) from exc

        filename = f"{prescription.prescription_number}.pdf"
        destination = self.pdf_path(filename)
        try:
            await asyncio.to_thread(destination.parent.mkdir, parents=True, exist_ok=True)
            await asyncio.to_thread(destination.write_bytes, content)
        except OSError as exc:
            raise PrescriptionError("The prescription PDF could not be stored.") from exc

        prescription.pdf_filename = filename
        prescription.pdf_generated_at = datetime.now(timezone.utc)
        await self.session.commit()
        logger.info(
            "prescription_pdf_generated",
            extra={"prescription_id": str(prescription_id), "bytes": len(content)},
        )
        return prescription

    @staticmethod
    def _follow_up_text(prescription: Prescription) -> Optional[str]:
        parts = []
        if prescription.follow_up_date:
            parts.append(prescription.follow_up_date.strftime("%d %b %Y"))
        if prescription.follow_up_notes:
            parts.append(prescription.follow_up_notes)
        return " — ".join(parts) if parts else None

    async def pdf_bytes(self, prescription_id: uuid.UUID) -> Optional[Tuple[Path, str]]:
        prescription = await self.get(prescription_id)
        if prescription is None or not prescription.pdf_filename:
            return None
        path = self.pdf_path(prescription.pdf_filename)
        exists = await asyncio.to_thread(path.exists)
        return (path, prescription.pdf_filename) if exists else None

    async def build_outbound_document(
        self, prescription_id: uuid.UUID
    ) -> Optional[OutboundDocument]:
        prescription = await self.get(prescription_id)
        if prescription is None:
            return None
        if not prescription.pdf_filename:
            await self.generate_pdf(prescription_id)
            prescription = await self.get(prescription_id)
        path = self.pdf_path(prescription.pdf_filename or "")
        if not await asyncio.to_thread(path.exists):
            return None
        patient_name = ""
        patient = await self.patients.get(prescription.patient_id)
        if patient:
            patient_name = patient.name
        caption = (
            f"{settings.HOSPITAL_NAME} — prescription for {patient_name}\n"
            f"Dr. {prescription.doctor_name.replace('Dr. ', '')} · "
            f"{DEPARTMENT_LABELS[prescription.department]}\n"
            f"Reference: {prescription.prescription_number}"
        )
        return OutboundDocument(
            filename=prescription.pdf_filename or "prescription.pdf",
            content=await asyncio.to_thread(path.read_bytes),
            content_type="application/pdf",
            caption=caption,
            public_url=self.public_document_url(prescription_id),
        )

    # -------------------------------------------------------------- delivery
    async def send_to_whatsapp(
        self, prescription_id: uuid.UUID, *, requested_by_name: str,
        override_number: Optional[str] = None,
    ) -> MessageDelivery:
        prescription = await self.get(prescription_id)
        if prescription is None:
            raise PrescriptionError("Prescription not found.")
        if prescription.status is not PrescriptionStatus.ISSUED:
            raise PrescriptionError("Issue the prescription before sending it.")

        patient = await self.patients.get(prescription.patient_id)
        recipient = override_number or (patient.phone_number if patient else "")
        if not recipient:
            raise PrescriptionError("This patient has no registered phone number.")

        delivery = await self.deliveries.queue(
            entity_type="prescription",
            entity_id=prescription.id,
            prescription_id=prescription.id,
            recipient_raw=recipient,
            requested_by_name=requested_by_name,
            channel=DeliveryChannel.WHATSAPP,
        )
        if delivery.is_final:      # unusable number, recorded as failed
            await self.session.commit()
            return delivery

        document = await self.build_outbound_document(prescription_id)
        if document is None:
            raise PrescriptionError("The prescription PDF is not available to send.")
        await self.deliveries.attempt(delivery, document)
        await self.session.commit()
        return delivery

    async def retry_delivery(
        self, delivery_id: uuid.UUID
    ) -> Optional[MessageDelivery]:
        delivery = await self.deliveries.get(delivery_id)
        if delivery is None:
            return None
        # A manual retry overrides the terminal flag: the doctor has decided to
        # try again, perhaps after correcting the number.
        delivery.is_final = False
        document = await self.build_outbound_document(delivery.entity_id)
        if document is None:
            raise PrescriptionError("The prescription PDF is not available to send.")
        await self.deliveries.attempt(delivery, document)
        await self.session.commit()
        return delivery

    # ------------------------------------------------------------- retrieval
    async def get(self, prescription_id: uuid.UUID) -> Optional[Prescription]:
        result = await self.session.execute(
            select(Prescription)
            .options(
                selectinload(Prescription.medicines),
                selectinload(Prescription.deliveries),
            )
            .where(Prescription.id == prescription_id)
        )
        return result.scalar_one_or_none()

    async def get_by_number(self, number: str) -> Optional[Prescription]:
        result = await self.session.execute(
            select(Prescription)
            .options(selectinload(Prescription.medicines))
            .where(Prescription.prescription_number == number)
        )
        return result.scalar_one_or_none()

    async def list_for(
        self,
        *,
        patient_id: Optional[uuid.UUID] = None,
        consultation_id: Optional[uuid.UUID] = None,
        limit: int = 50,
    ) -> List[Prescription]:
        statement = (
            select(Prescription)
            .options(
                selectinload(Prescription.medicines),
                selectinload(Prescription.deliveries),
            )
            .order_by(Prescription.created_at.desc())
            .limit(limit)
        )
        if patient_id is not None:
            statement = statement.where(Prescription.patient_id == patient_id)
        if consultation_id is not None:
            statement = statement.where(Prescription.consultation_id == consultation_id)
        result = await self.session.execute(statement)
        return list(result.scalars().all())

    async def cancel(self, prescription_id: uuid.UUID) -> Optional[Prescription]:
        prescription = await self.get(prescription_id)
        if prescription is None:
            return None
        prescription.status = PrescriptionStatus.CANCELLED
        await self.session.commit()
        return prescription
